version: "3.7"

services:
  parser:
    build:
      context: .
    image: jibrel/notable-accounts-parser
    environment:
      DB_DSN: postgres://postgres:postgres@db:5432/db
    command: jibrel-notable-accounts-parser

  dev:
    build:
      args:
        ENVIRONMENT: development
      context: .
    image: jibrel/notable-accounts-dev
    volumes:
      - ./:/app

  db:
    image: postgres:11-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

volumes:
  db:
