version: "3.7"

services:
  parser:
    build:
      context: .
    image: jibrel/notable-accounts-parser
    command: jibrel-notable-accounts-parser
  dev:
    build:
      args:
        ENVIRONMENT: development
      context: .
    image: jibrel/notable-accounts-dev
    volumes:
    - ./:/app
